name="Zeeshan Ahmad Khalil"
console.log(name.length)
console.log(name.indexOf("A"))
console.log(name.indexOf("h"))
console.log(name.lastIndexOf("h"))
console.log(name.indexOf("x"))
console.log(name.lastIndexOf("Zeeshan"))
console.log(name.lastIndexOf("Zeeshan",12))
console.log(name.lastIndexOf("a",12))
console.log(name.lastIndexOf("a",10))
console.log(name.search("x"))
console.log(name.search("m"))
console.log()
console.log(name.slice(3,7))
console.log(name.slice(13,7)) //empty
console.log(name.slice(-3,21))
console.log()
console.log(name.substring(3,7))
// console.log(name.substring(13,7)) 
console.log(name.substring(-3,21))
console.log()
console.log(name.substr(3,4))
// console.log(name.substr(13,7)) 
console.log(name.substr(-4,4))
console.log()
console.log(name.replace("Khalil","khalil"))
dummy="me me me"
console.log(dummy.replace("me","my"))
console.log(dummy)
console.log(dummy.replace(/ME/i,"my"))
console.log(name.toUpperCase())
console.log(name.toLowerCase())
nick_name="         moon      "
console.log(nick_name.trim())
console.log(nick_name)
names="zeeshan,faizan,mubeen"
console.log(names.split(","))
console.log(names.split(" "))
console.log(names.split(""))
console.log(names.split("n"))