a=123
console.log(a.toString())
deciaml=123
binary=deciaml.toString(2)
console.log(binary)
b=234
console.log((a+b).toString())
c=123455678.12345678
console.log(c.toExponential())
console.log(c.toExponential(10))
console.log(c.toExponential(2))
d=12345.12345
console.log(d.toFixed(5))
console.log(d.toPrecision(5))
e=20
console.log(e.valueOf())
console.log("\n")
console.log(Number(true))
console.log(Number(" 10"))
console.log(Number("10 "))
console.log(Number(" 10 "))
console.log(Number("10.33"))
console.log(Number("10,33"))
console.log(Number("john"))
console.log(Number(new Date(2020-1-22)))
console.log("\n")
console.log(parseInt(true))
console.log(parseInt(" 10"))
console.log(parseInt("10 "))
console.log(parseInt(" 10 "))
console.log(parseInt("10.33"))
console.log(parseInt("10,33"))
console.log(parseInt("john"))
console.log(parseInt(new Date(2020-1-22)))
console.log("\n")
console.log(parseFloat(true))
console.log(parseFloat(" 10"))
console.log(parseFloat("10 "))
console.log(parseFloat(" 10 "))
console.log(parseFloat("10.33"))
console.log(parseFloat("10,33"))
console.log(parseFloat("john"))
console.log(parseFloat(new Date(2020-1-22)))
console.log("\n")
console.log(binary)
console.log(parseInt(binary,2))
console.log("\n")
console.log(Number.MAX_VALUE)
console.log(Number.MIN_VALUE)
console.log(Number.POSITIVE_INFINITY)
console.log(Number.NEGATIVE_INFINITY)
console.log("\n")
console.log(Object.MAX_VALUE)
console.log(Object.MIN_VALUE)
console.log(Object.POSITIVE_INFINITY)
console.log(Object.NEGATIVE_INFINITY)
console.log("\n")
console.log(String.MAX_VALUE)
console.log(String.MIN_VALUE)
console.log(String.POSITIVE_INFINITY)
console.log(String.NEGATIVE_INFINITY)
console.log(1/0)
console.log(-1/0)
x=7
console.log(x.MAX_VALUE)