names=["zeeshan","faizan","mubeen"]
a=names.toString()
console.log(a)
console.log(a.constructor)
a=names.join()
console.log(a)
a=names.join("-")
console.log(a)
console.log(names.pop())
console.log(names)
names.push("Iqra")
console.log(names)
console.log(names.shift())
names.unshift("moon")
console.log(names)
names[0]="Zeeshan"
console.log(names)
names[names.length]="Mubeen"
console.log(names)
other_names=["salma","hina","kiren"]
names=names.concat(other_names)
console.log(names)
more_names=["bilal","hamza","salman"]
alphabets="A,B,C"
names=names.concat(more_names,alphabets)
console.log(names)
girls=names.slice(4,7)
console.log(girls)
console.log(names)
